require 'set'
require 'minitest/autorun'
require_relative 'test_libtree'
require_relative 'test_homomorphism'
require_relative 'test_automaton'
require_relative 'test_grammar'
require_relative 'test_regular_expression'
require_relative 'test_capture'
